import { createElement } from "react";
import {
  Blocks,
  Boxes,
  Box,
  CloudCog,
  Cloud,
  Circle,
  Component,
  Container,
  CreditCard,
  Database,
  DatabaseZap,
  Diamond,
  Gauge,
  Globe2,
  HardDrive,
  Image as ImageIcon,
  Layers3,
  Lightbulb,
  Mail,
  MapPin,
  MapPinned,
  MessageSquareMore,
  Minus,
  Monitor,
  Network,
  PanelsTopLeft,
  PlugZap,
  Puzzle,
  RadioTower,
  RectangleHorizontal,
  Route,
  Rows3,
  Search,
  Send,
  Server,
  ShipWheel,
  ShieldCheck,
  SquareRoundCorner,
  Smartphone,
  StickyNote,
  Tag,
  TriangleAlert,
  Type,
  User,
  Warehouse,
  Waves,
  Waypoints,
  Workflow,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import { getSystemDesignNodeDefinition } from "../constants/system-design-palette";
import type {
  SystemDesignIconKey,
  SystemDesignNodeType,
} from "../types/system-design.types";

const nodeIcons: Record<SystemDesignIconKey, LucideIcon> = {
  user: User,
  browser: Monitor,
  mobile: Smartphone,
  admin: ShieldCheck,
  globe: Globe2,
  network: Network,
  route: Waypoints,
  gateway: Route,
  server: Server,
  boxes: Boxes,
  box: Box,
  worker: Component,
  function: CloudCog,
  database: Database,
  "document-database": DatabaseZap,
  cache: Gauge,
  search: Search,
  storage: HardDrive,
  warehouse: Warehouse,
  queue: Send,
  stream: Waves,
  broadcast: RadioTower,
  "external-link": PlugZap,
  payment: CreditCard,
  notification: Mail,
  email: Mail,
  sms: Smartphone,
  "identity-provider": ShieldCheck,
  module: Blocks,
  "logical-module": Blocks,
  "feature-module": Puzzle,
  "domain-module": Boxes,
  boundary: Container,
  "module-boundary": PanelsTopLeft,
  vpc: Cloud,
  region: MapPinned,
  "availability-zone": MapPin,
  "kubernetes-cluster": ShipWheel,
  "deployment-group": Layers3,
  swimlane: Rows3,
  container: Box,
  text: Type,
  note: StickyNote,
  "warning-note": TriangleAlert,
  "assumption-note": Lightbulb,
  rectangle: RectangleHorizontal,
  "rounded-rectangle": SquareRoundCorner,
  ellipse: Circle,
  diamond: Diamond,
  callout: MessageSquareMore,
  divider: Minus,
  label: Tag,
  image: ImageIcon,
};

export function getSystemDesignNodeIcon(type: SystemDesignNodeType): LucideIcon {
  return nodeIcons[getSystemDesignNodeDefinition(type).iconKey];
}

export function SystemDesignNodeIcon({
  type,
  ...props
}: LucideProps & { type: SystemDesignNodeType }) {
  return createElement(getSystemDesignNodeIcon(type), {
    "aria-hidden": true,
    ...props,
  });
}

export function SystemDesignWorkflowIcon(props: LucideProps) {
  return <Workflow aria-hidden="true" {...props} />;
}
