import type {
  SystemDesignNodeCategory,
  SystemDesignNodeDefinition,
  SystemDesignNodeType,
  SystemDesignPaletteCategory,
} from "../types/system-design.types";

export const SYSTEM_DESIGN_NODE_TYPE_ORDER = [
  "user",
  "web_app",
  "mobile_app",
  "admin_portal",
  "dns",
  "cdn",
  "load_balancer",
  "api_gateway",
  "service",
  "microservice",
  "monolith",
  "worker",
  "serverless_function",
  "sql_database",
  "nosql_database",
  "cache",
  "search_engine",
  "object_storage",
  "data_warehouse",
  "message_queue",
  "event_stream",
  "pubsub",
  "third_party_api",
  "payment_provider",
  "notification_provider",
] as const satisfies readonly SystemDesignNodeType[];

export const SYSTEM_DESIGN_NODE_DEFINITIONS = {
  user: {
    type: "user",
    category: "clients",
    label: "User",
    tooltip: "A person or client identity that initiates requests.",
    iconKey: "user",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  web_app: {
    type: "web_app",
    category: "clients",
    label: "Web Application",
    tooltip: "A browser-based frontend delivered to desktop or mobile users.",
    iconKey: "browser",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  mobile_app: {
    type: "mobile_app",
    category: "clients",
    label: "Mobile Application",
    tooltip: "A native or cross-platform mobile client.",
    iconKey: "mobile",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  admin_portal: {
    type: "admin_portal",
    category: "clients",
    label: "Admin Portal",
    tooltip: "An internal interface used to operate or moderate the system.",
    iconKey: "admin",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  dns: {
    type: "dns",
    category: "networking",
    label: "DNS",
    tooltip: "A domain name service that resolves names to endpoints.",
    iconKey: "globe",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  cdn: {
    type: "cdn",
    category: "networking",
    label: "CDN",
    tooltip: "A content delivery network that caches assets near users.",
    iconKey: "network",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  load_balancer: {
    type: "load_balancer",
    category: "networking",
    label: "Load Balancer",
    tooltip: "A traffic distributor for a pool of healthy service instances.",
    iconKey: "route",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  api_gateway: {
    type: "api_gateway",
    category: "networking",
    label: "API Gateway",
    tooltip: "An API entry point for routing, authentication, and policies.",
    iconKey: "gateway",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  service: {
    type: "service",
    category: "compute",
    label: "Service",
    tooltip: "A deployable backend service with a focused responsibility.",
    iconKey: "server",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  microservice: {
    type: "microservice",
    category: "compute",
    label: "Microservice",
    tooltip: "An independently deployable service within a larger system.",
    iconKey: "boxes",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  monolith: {
    type: "monolith",
    category: "compute",
    label: "Monolith",
    tooltip: "A single deployable application containing multiple capabilities.",
    iconKey: "box",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  worker: {
    type: "worker",
    category: "compute",
    label: "Worker",
    tooltip: "A background process that consumes and executes asynchronous work.",
    iconKey: "worker",
    defaultWidth: 150,
    defaultHeight: 84,
  },
  serverless_function: {
    type: "serverless_function",
    category: "compute",
    label: "Serverless Function",
    tooltip: "An event-triggered unit of compute managed by a cloud provider.",
    iconKey: "function",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  sql_database: {
    type: "sql_database",
    category: "data",
    label: "SQL Database",
    tooltip: "A relational database with transactions and structured schemas.",
    iconKey: "database",
    defaultWidth: 170,
    defaultHeight: 92,
  },
  nosql_database: {
    type: "nosql_database",
    category: "data",
    label: "NoSQL Database",
    tooltip: "A non-relational database optimized for flexible or distributed data.",
    iconKey: "document-database",
    defaultWidth: 180,
    defaultHeight: 92,
  },
  cache: {
    type: "cache",
    category: "data",
    label: "Cache",
    tooltip: "A fast temporary store used to reduce latency and backend load.",
    iconKey: "cache",
    defaultWidth: 150,
    defaultHeight: 84,
  },
  search_engine: {
    type: "search_engine",
    category: "data",
    label: "Search Engine",
    tooltip: "An indexed store for full-text search and relevance queries.",
    iconKey: "search",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  object_storage: {
    type: "object_storage",
    category: "data",
    label: "Object Storage",
    tooltip: "Durable blob storage for files and other unstructured objects.",
    iconKey: "storage",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  data_warehouse: {
    type: "data_warehouse",
    category: "data",
    label: "Data Warehouse",
    tooltip: "An analytical store for large-scale reporting and aggregation.",
    iconKey: "warehouse",
    defaultWidth: 180,
    defaultHeight: 92,
  },
  message_queue: {
    type: "message_queue",
    category: "messaging",
    label: "Message Queue",
    tooltip: "A durable queue that buffers work between producers and consumers.",
    iconKey: "queue",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  event_stream: {
    type: "event_stream",
    category: "messaging",
    label: "Event Stream",
    tooltip: "An ordered, replayable log of events for multiple consumers.",
    iconKey: "stream",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  pubsub: {
    type: "pubsub",
    category: "messaging",
    label: "Pub/Sub Topic",
    tooltip: "A topic that fans published messages out to subscribers.",
    iconKey: "broadcast",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  third_party_api: {
    type: "third_party_api",
    category: "external",
    label: "Third-Party API",
    tooltip: "An external service API outside the system's operational control.",
    iconKey: "external-link",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  payment_provider: {
    type: "payment_provider",
    category: "external",
    label: "Payment Provider",
    tooltip: "An external processor for payment authorization and settlement.",
    iconKey: "payment",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  notification_provider: {
    type: "notification_provider",
    category: "external",
    label: "Email or SMS Provider",
    tooltip: "An external provider that delivers email, SMS, or push messages.",
    iconKey: "notification",
    defaultWidth: 190,
    defaultHeight: 88,
  },
} as const satisfies Record<SystemDesignNodeType, SystemDesignNodeDefinition>;

const CATEGORY_ORDER = [
  ["clients", "Clients"],
  ["networking", "Networking"],
  ["compute", "Compute"],
  ["data", "Data"],
  ["messaging", "Messaging"],
  ["external", "External"],
] as const satisfies readonly (readonly [SystemDesignNodeCategory, string])[];

export const SYSTEM_DESIGN_PALETTE_CATEGORIES: readonly SystemDesignPaletteCategory[] =
  CATEGORY_ORDER.map(([id, label]) => ({
    id,
    label,
    items: SYSTEM_DESIGN_NODE_TYPE_ORDER.filter(
      (type) => SYSTEM_DESIGN_NODE_DEFINITIONS[type].category === id,
    ).map((type) => SYSTEM_DESIGN_NODE_DEFINITIONS[type]),
  }));

export function getSystemDesignNodeDefinition(
  type: SystemDesignNodeType,
): SystemDesignNodeDefinition {
  return SYSTEM_DESIGN_NODE_DEFINITIONS[type];
}
