import type {
  SystemDesignNodeCategory,
  SystemDesignNodeDefinition,
  SystemDesignNodeType,
  SystemDesignPaletteCategory,
} from "../types/system-design.types";

export const SYSTEM_DESIGN_NODE_TYPE_ORDER = [
  "user",
  "web_app",
  "mobile_app",
  "admin_portal",
  "dns",
  "cdn",
  "load_balancer",
  "api_gateway",
  "service",
  "microservice",
  "monolith",
  "worker",
  "serverless_function",
  "sql_database",
  "nosql_database",
  "cache",
  "search_engine",
  "object_storage",
  "data_warehouse",
  "message_queue",
  "event_stream",
  "pubsub",
  "third_party_api",
  "payment_provider",
  "notification_provider",
  "email_provider",
  "sms_provider",
  "identity_provider",
  "module",
  "logical_module",
  "feature_module",
  "domain_module",
  "system_boundary",
  "module_boundary",
  "vpc_boundary",
  "region_boundary",
  "availability_zone_boundary",
  "kubernetes_cluster_boundary",
  "deployment_group_boundary",
  "swimlane_boundary",
  "container",
  "text",
  "note",
  "warning_note",
  "assumption_note",
  "rectangle",
  "rounded_rectangle",
  "ellipse",
  "diamond",
  "callout",
  "divider",
  "label",
] as const satisfies readonly SystemDesignNodeType[];

export const SYSTEM_DESIGN_NODE_DEFINITIONS = {
  user: {
    type: "user",
    category: "clients",
    label: "User",
    tooltip: "A person or client identity that initiates requests.",
    iconKey: "user",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  web_app: {
    type: "web_app",
    category: "clients",
    label: "Web Application",
    tooltip: "A browser-based frontend delivered to desktop or mobile users.",
    iconKey: "browser",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  mobile_app: {
    type: "mobile_app",
    category: "clients",
    label: "Mobile Application",
    tooltip: "A native or cross-platform mobile client.",
    iconKey: "mobile",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  admin_portal: {
    type: "admin_portal",
    category: "clients",
    label: "Admin Portal",
    tooltip: "An internal interface used to operate or moderate the system.",
    iconKey: "admin",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  dns: {
    type: "dns",
    category: "networking",
    label: "DNS",
    tooltip: "A domain name service that resolves names to endpoints.",
    iconKey: "globe",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  cdn: {
    type: "cdn",
    category: "networking",
    label: "CDN",
    tooltip: "A content delivery network that caches assets near users.",
    iconKey: "network",
    defaultWidth: 140,
    defaultHeight: 80,
  },
  load_balancer: {
    type: "load_balancer",
    category: "networking",
    label: "Load Balancer",
    tooltip: "A traffic distributor for a pool of healthy service instances.",
    iconKey: "route",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  api_gateway: {
    type: "api_gateway",
    category: "networking",
    label: "API Gateway",
    tooltip: "An API entry point for routing, authentication, and policies.",
    iconKey: "gateway",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  service: {
    type: "service",
    category: "compute",
    label: "Service",
    tooltip: "A deployable backend service with a focused responsibility.",
    iconKey: "server",
    defaultWidth: 160,
    defaultHeight: 88,
  },
  microservice: {
    type: "microservice",
    category: "compute",
    label: "Microservice",
    tooltip: "An independently deployable service within a larger system.",
    iconKey: "boxes",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  monolith: {
    type: "monolith",
    category: "compute",
    label: "Monolith",
    tooltip: "A single deployable application containing multiple capabilities.",
    iconKey: "box",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  worker: {
    type: "worker",
    category: "compute",
    label: "Worker",
    tooltip: "A background process that consumes and executes asynchronous work.",
    iconKey: "worker",
    defaultWidth: 150,
    defaultHeight: 84,
  },
  serverless_function: {
    type: "serverless_function",
    category: "compute",
    label: "Serverless Function",
    tooltip: "An event-triggered unit of compute managed by a cloud provider.",
    iconKey: "function",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  sql_database: {
    type: "sql_database",
    category: "data",
    label: "SQL Database",
    tooltip: "A relational database with transactions and structured schemas.",
    iconKey: "database",
    defaultWidth: 170,
    defaultHeight: 92,
  },
  nosql_database: {
    type: "nosql_database",
    category: "data",
    label: "NoSQL Database",
    tooltip: "A non-relational database optimized for flexible or distributed data.",
    iconKey: "document-database",
    defaultWidth: 180,
    defaultHeight: 92,
  },
  cache: {
    type: "cache",
    category: "data",
    label: "Cache",
    tooltip: "A fast temporary store used to reduce latency and backend load.",
    iconKey: "cache",
    defaultWidth: 150,
    defaultHeight: 84,
  },
  search_engine: {
    type: "search_engine",
    category: "data",
    label: "Search Engine",
    tooltip: "An indexed store for full-text search and relevance queries.",
    iconKey: "search",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  object_storage: {
    type: "object_storage",
    category: "data",
    label: "Object Storage",
    tooltip: "Durable blob storage for files and other unstructured objects.",
    iconKey: "storage",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  data_warehouse: {
    type: "data_warehouse",
    category: "data",
    label: "Data Warehouse",
    tooltip: "An analytical store for large-scale reporting and aggregation.",
    iconKey: "warehouse",
    defaultWidth: 180,
    defaultHeight: 92,
  },
  message_queue: {
    type: "message_queue",
    category: "messaging",
    label: "Message Queue",
    tooltip: "A durable queue that buffers work between producers and consumers.",
    iconKey: "queue",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  event_stream: {
    type: "event_stream",
    category: "messaging",
    label: "Event Stream",
    tooltip: "An ordered, replayable log of events for multiple consumers.",
    iconKey: "stream",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  pubsub: {
    type: "pubsub",
    category: "messaging",
    label: "Pub/Sub Topic",
    tooltip: "A topic that fans published messages out to subscribers.",
    iconKey: "broadcast",
    defaultWidth: 170,
    defaultHeight: 88,
  },
  third_party_api: {
    type: "third_party_api",
    category: "external",
    label: "Third-Party API",
    tooltip: "An external service API outside the system's operational control.",
    iconKey: "external-link",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  payment_provider: {
    type: "payment_provider",
    category: "external",
    label: "Payment Provider",
    tooltip: "An external processor for payment authorization and settlement.",
    iconKey: "payment",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  notification_provider: {
    type: "notification_provider",
    category: "external",
    label: "Email or SMS Provider",
    tooltip: "An external provider that delivers email, SMS, or push messages.",
    iconKey: "notification",
    defaultWidth: 190,
    defaultHeight: 88,
  },
  email_provider: {
    type: "email_provider",
    category: "external",
    label: "Email Provider",
    tooltip: "An external provider that delivers transactional or bulk email.",
    iconKey: "email",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  sms_provider: {
    type: "sms_provider",
    category: "external",
    label: "SMS Provider",
    tooltip: "An external provider that delivers SMS or phone notifications.",
    iconKey: "sms",
    defaultWidth: 180,
    defaultHeight: 88,
  },
  identity_provider: {
    type: "identity_provider",
    category: "external",
    label: "Identity Provider",
    tooltip: "An external identity service for authentication and federation.",
    iconKey: "identity-provider",
    defaultWidth: 190,
    defaultHeight: 88,
  },
  module: {
    type: "module",
    category: "modules",
    label: "Module",
    tooltip:
      "An expandable logical subsystem that can contain its own architecture diagram.",
    iconKey: "module",
    defaultWidth: 220,
    defaultHeight: 120,
  },
  logical_module: {
    type: "logical_module",
    category: "modules",
    label: "Logical Module",
    tooltip: "An expandable subsystem grouped by a logical responsibility.",
    iconKey: "logical-module",
    defaultWidth: 220,
    defaultHeight: 120,
  },
  feature_module: {
    type: "feature_module",
    category: "modules",
    label: "Feature Module",
    tooltip: "An expandable product capability such as Authentication or Search.",
    iconKey: "feature-module",
    defaultWidth: 220,
    defaultHeight: 120,
  },
  domain_module: {
    type: "domain_module",
    category: "modules",
    label: "Domain Module",
    tooltip: "An expandable bounded domain such as Payments or Order Processing.",
    iconKey: "domain-module",
    defaultWidth: 220,
    defaultHeight: 120,
  },
  system_boundary: {
    type: "system_boundary",
    category: "boundaries",
    label: "System Boundary",
    tooltip:
      "A labeled trust, ownership, or deployment boundary around related components.",
    iconKey: "boundary",
    defaultWidth: 320,
    defaultHeight: 220,
  },
  module_boundary: {
    type: "module_boundary",
    category: "boundaries",
    label: "Module Boundary",
    tooltip: "A structural boundary around services owned by one logical module.",
    iconKey: "module-boundary",
    defaultWidth: 300,
    defaultHeight: 200,
  },
  vpc_boundary: {
    type: "vpc_boundary",
    category: "boundaries",
    label: "VPC Boundary",
    tooltip: "A virtual private cloud or isolated network boundary.",
    iconKey: "vpc",
    defaultWidth: 380,
    defaultHeight: 260,
  },
  region_boundary: {
    type: "region_boundary",
    category: "boundaries",
    label: "Cloud Region",
    tooltip: "A cloud provider region containing availability zones and workloads.",
    iconKey: "region",
    defaultWidth: 420,
    defaultHeight: 300,
  },
  availability_zone_boundary: {
    type: "availability_zone_boundary",
    category: "boundaries",
    label: "Availability Zone",
    tooltip: "A failure-isolated availability zone within a cloud region.",
    iconKey: "availability-zone",
    defaultWidth: 340,
    defaultHeight: 240,
  },
  kubernetes_cluster_boundary: {
    type: "kubernetes_cluster_boundary",
    category: "boundaries",
    label: "Kubernetes Cluster",
    tooltip: "A Kubernetes cluster boundary around deployed workloads and services.",
    iconKey: "kubernetes-cluster",
    defaultWidth: 380,
    defaultHeight: 260,
  },
  deployment_group_boundary: {
    type: "deployment_group_boundary",
    category: "boundaries",
    label: "Deployment Group",
    tooltip: "A group of components deployed, scaled, or released together.",
    iconKey: "deployment-group",
    defaultWidth: 320,
    defaultHeight: 220,
  },
  swimlane_boundary: {
    type: "swimlane_boundary",
    category: "boundaries",
    label: "Swimlane",
    tooltip: "A horizontal responsibility lane for a team, system, or process stage.",
    iconKey: "swimlane",
    defaultWidth: 480,
    defaultHeight: 150,
  },
  container: {
    type: "container",
    category: "boundaries",
    label: "Container",
    tooltip:
      "A visual container for services that share a runtime or deployment unit.",
    iconKey: "container",
    defaultWidth: 260,
    defaultHeight: 180,
  },
  text: {
    type: "text",
    category: "annotations",
    label: "Free Text",
    tooltip: "A lightweight text annotation for explaining architectural decisions.",
    iconKey: "text",
    defaultWidth: 180,
    defaultHeight: 72,
  },
  note: {
    type: "note",
    category: "annotations",
    label: "Note",
    tooltip: "A sticky note for assumptions, risks, and design trade-offs.",
    iconKey: "note",
    defaultWidth: 180,
    defaultHeight: 120,
  },
  warning_note: {
    type: "warning_note",
    category: "annotations",
    label: "Warning Note",
    tooltip: "A prominent annotation for a risk, failure mode, or operational concern.",
    iconKey: "warning-note",
    defaultWidth: 190,
    defaultHeight: 120,
  },
  assumption_note: {
    type: "assumption_note",
    category: "annotations",
    label: "Assumption Note",
    tooltip: "An annotation that records a design assumption or constraint.",
    iconKey: "assumption-note",
    defaultWidth: 190,
    defaultHeight: 120,
  },
  rectangle: {
    type: "rectangle",
    category: "annotations",
    label: "Rectangle",
    tooltip: "A plain rectangular annotation shape.",
    iconKey: "rectangle",
    defaultWidth: 180,
    defaultHeight: 100,
  },
  rounded_rectangle: {
    type: "rounded_rectangle",
    category: "annotations",
    label: "Rounded Rectangle",
    tooltip: "A rounded annotation shape for lightweight callouts or grouping.",
    iconKey: "rounded-rectangle",
    defaultWidth: 180,
    defaultHeight: 100,
  },
  ellipse: {
    type: "ellipse",
    category: "annotations",
    label: "Ellipse",
    tooltip: "An elliptical annotation shape.",
    iconKey: "ellipse",
    defaultWidth: 170,
    defaultHeight: 110,
  },
  diamond: {
    type: "diamond",
    category: "annotations",
    label: "Decision Diamond",
    tooltip: "A diamond annotation for decisions or conditional paths.",
    iconKey: "diamond",
    defaultWidth: 150,
    defaultHeight: 120,
  },
  callout: {
    type: "callout",
    category: "annotations",
    label: "Callout",
    tooltip: "A speech-style callout for focused explanatory text.",
    iconKey: "callout",
    defaultWidth: 190,
    defaultHeight: 120,
  },
  divider: {
    type: "divider",
    category: "annotations",
    label: "Divider",
    tooltip: "A visual divider for separating regions of a diagram.",
    iconKey: "divider",
    defaultWidth: 240,
    defaultHeight: 72,
  },
  label: {
    type: "label",
    category: "annotations",
    label: "Label",
    tooltip: "A compact text label for naming regions or flows.",
    iconKey: "label",
    defaultWidth: 160,
    defaultHeight: 72,
  },
  image: {
    type: "image",
    category: "annotations",
    label: "Embedded Image",
    tooltip: "A safely embedded raster image or sanitized SVG asset.",
    iconKey: "image",
    defaultWidth: 240,
    defaultHeight: 160,
  },
} as const satisfies Record<SystemDesignNodeType, SystemDesignNodeDefinition>;

const CATEGORY_ORDER = [
  ["clients", "Clients"],
  ["networking", "Networking"],
  ["compute", "Compute"],
  ["data", "Data"],
  ["messaging", "Messaging"],
  ["external", "External"],
  ["modules", "Modules"],
  ["boundaries", "Boundaries"],
  ["annotations", "Annotations"],
] as const satisfies readonly (readonly [SystemDesignNodeCategory, string])[];

export const SYSTEM_DESIGN_PALETTE_CATEGORIES: readonly SystemDesignPaletteCategory[] =
  CATEGORY_ORDER.map(([id, label]) => ({
    id,
    label,
    items: SYSTEM_DESIGN_NODE_TYPE_ORDER.filter(
      (type) => SYSTEM_DESIGN_NODE_DEFINITIONS[type].category === id,
    ).map((type) => SYSTEM_DESIGN_NODE_DEFINITIONS[type]),
  }));

export function getSystemDesignNodeDefinition(
  type: SystemDesignNodeType,
): SystemDesignNodeDefinition {
  return SYSTEM_DESIGN_NODE_DEFINITIONS[type];
}

export const SYSTEM_DESIGN_MODULE_NODE_TYPES = [
  "module",
  "logical_module",
  "feature_module",
  "domain_module",
] as const satisfies readonly SystemDesignNodeType[];

export const SYSTEM_DESIGN_BOUNDARY_NODE_TYPES = [
  "system_boundary",
  "module_boundary",
  "vpc_boundary",
  "region_boundary",
  "availability_zone_boundary",
  "kubernetes_cluster_boundary",
  "deployment_group_boundary",
  "swimlane_boundary",
  "container",
] as const satisfies readonly SystemDesignNodeType[];

const MODULE_NODE_TYPE_SET = new Set<SystemDesignNodeType>(
  SYSTEM_DESIGN_MODULE_NODE_TYPES,
);
const BOUNDARY_NODE_TYPE_SET = new Set<SystemDesignNodeType>(
  SYSTEM_DESIGN_BOUNDARY_NODE_TYPES,
);

export function isSystemDesignModuleNodeType(
  type: SystemDesignNodeType,
): boolean {
  return MODULE_NODE_TYPE_SET.has(type);
}

export function isSystemDesignBoundaryNodeType(
  type: SystemDesignNodeType,
): boolean {
  return BOUNDARY_NODE_TYPE_SET.has(type);
}
